# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'Installing Modules in /client-main'
  inputs:
    command: 'install'
    workingDir: 'client-main'
- task: Npm@1
  displayName: 'Installing Modules in /server-main'
  inputs:
    command: 'install'
    workingDir: 'server-main'
- task: CopyFiles@2
  inputs:
    Contents: |
      client-main/dist/**
      server-main/**
    TargetFolder: 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'
- task: Npm@1
  displayName: 'Building  Modules in /client-main'
  inputs:
    command: 'custom'
    workingDir: 'client-main'
    customCommand: 'run build'
